### ISSUE TITLE
templates: go-check should strip version comments before comparing go generate output

### ISSUE THREAD

**Issue by galargh** [pl-strflt/uci#26]
See https://github.com/libp2p/go-libp2p/issues/2429 for details

**Comment by marten-seemann** [comment]
Interesting idea to move this to uCI. Are we ok hardcoding assumptions how people use `go generate` here?

**Comment by galargh** [comment]
My initial thinking was adding an opt-in for that in uCI and then enabling it in go-libp2p. So we wouldn't be changing the behaviour for everyone by default but if someone needed it, it'd be easy to get.
